version: '3'
services:
  app:
    build: . # Use the local Dockerfile to build the image for this service
    ports:
      - 4000:3000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=12345678
